# Generated by Django 6.0.6 on 2026-06-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=5)),
                ('altura_cm', models.IntegerField(help_text='Altura en centímetros')),
                ('dieta_recomendada', models.TextField()),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('miembro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gym.miembro')),
            ],
        ),
    ]
